apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-ovh-prod
spec:
  acme:
    email: "pierre.h001002@gmail.com"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-ovh-prod-account-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.mycompany.example
            solverName: ovh
            config:
              endpoint: ovh-eu
              applicationKey: "351565ee6eff35a9"
              consumerKey: "e7315e30d7ef24bffbee9cfea2b6bbd5"
              applicationSecretRef:
                name: ovh-dns-credentials
                key: applicationSecret
