apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  sources:
    - repoURL: https://github.com/PierreH2/homelab.git
      targetRevision: main
      ref: values
    - repoURL: docker.io/envoyproxy
      chart: gateway-helm
      targetRevision: v1.6.1
      helm:
        valueFiles:
          - $values/apps/envoy-gateway-system/values/values.yaml
    - repoURL: https://github.com/PierreH2/homelab.git
      targetRevision: main
      path: apps/envoy-gateway-system/config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: ""
      kind: Service
      name: envoy-envoy-gateway-system-eg-*
      jqPathExpressions:
        - .spec
        - .metadata.annotations
        - .metadata.finalizers
        - .metadata.ownerReferences
    - group: ""
      kind: Service
      jqPathExpressions:
        - .spec.clusterIP
        - .spec.clusterIPs
        - .spec.healthCheckNodePort
        - .spec.ports[].nodePort
        - .metadata.annotations
        - .metadata.finalizers
    - group: gateway.networking.k8s.io
      kind: Gateway
      jqPathExpressions:
        - .status
        - .metadata.annotations
        - .metadata.finalizers
