apiVersion: v1
kind: PersistentVolume
metadata:
  name: apache-nas-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 198.162.1.100
    path: /data/nas/public/apache
