apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  sources:
    - repoURL: https://github.com/PierreH2/homelab.git
      targetRevision: main
      path: apps/cert-manager/prerequisite
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.14.4
      helm:
        values: |
          installCRDs: true
    - repoURL: https://github.com/PierreH2/homelab.git
      targetRevision: main
      path: apps/cert-manager/yaml
    - repoURL: https://github.com/PierreH2/homelab.git
      targetRevision: main
      path: apps/cert-manager/config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true