apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: harbor-hostpath
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-nas-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-hostpath
  hostPath:
    path: /data/nas/public/registry
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-nas-pvc
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: harbor-hostpath
  resources:
    requests:
      storage: 25Gi
