# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: piron-homelab-ca
# spec:
#   ca:
#     secretName: piron-homelab-ca
# ---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-ovh-prod
spec:
  acme:
    email: admin@piron-tech.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-ovh-prod-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.mycompany.example
            solverName: ovh
            config:
              endpoint: ovh-eu
              applicationKeySecretRef:
                name: ovh-dns-credentials
                key: applicationKey
              applicationSecretSecretRef:
                name: ovh-dns-credentials
                key: applicationSecret
              consumerKeySecretRef:
                name: ovh-dns-credentials
                key: consumerKey

