server:
  retention: "4d"
  retentionSize: "10GB"

  service:
    enabled: true
    servicePort: 80
    servicePortName: http   

  global:
    scrape_interval: 15s

  resources:
    limits:
      cpu: 2000m
      memory: 2Gi

  persistentVolume:
    enabled: false

  storagePath: /prometheus-data

  extraHostPathMounts:
    - name: prometheus-storage
      mountPath: /prometheus-data
      hostPath: /data/nas/private/prometheus
      readOnly: false

  extraInitContainers: []

# Désactiver l'annotation prometheus.io/scrape sur kube-state-metrics
# car on utilise une config statique dans serverFiles
kube-state-metrics:
  prometheusScrape: false

# Utiliser la découverte automatique pour node-exporter
prometheus-node-exporter:
  prometheusScrape: true

serverFiles:
  prometheus.yml:
    scrape_configs:

      - job_name: kube-state-metrics
        static_configs:
          - targets:
              - prometheus-kube-state-metrics.prometheus.svc.cluster.local:8080
