apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  sources:
    - repoURL: https://github.com/PierreH2/homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/PierreH2/homelab.git
      targetRevision: main
      path: apps/harbor/prerequisite
      syncWave: 0
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: "1.18.*"
      syncWave: 1
      helm:
        releaseName: harbor
        valueFiles:
          - $values/apps/harbor/values/values.yaml
    - repoURL: https://github.com/PierreH2/homelab.git
      targetRevision: main
      path: apps/harbor/yaml
      syncWave: 2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
