service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 300m
    memory: 1Gi

persistence:
  enabled: true
  type: pvc
  existingClaim: grafana-pvc

initChownData:
  enabled: false

grafana.ini:
  server:
    root_url: "https://grafana.piron-tech.com/"
    serve_from_sub_path: false




# If you use Gateway API, usually keep classic ingress disabled
ingress:
  enabled: false

# Gateway API (BETA in this chart)
# HTTPRoute managed in yaml/httproute.yaml instead
route:
  main:
    enabled: false
